server:
  port: 8080

spring:
  application:
    name: bapsim-app
  
  datasource:
    url: jdbc:mysql://mysql:3306/bapsim_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        enable_lazy_load_no_trans: false
  
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  
  sql:
    init:
      mode: never

logging:
  level:
    com.bapsim: DEBUG
    org.springframework.web: DEBUG
