spring:
  datasource:
    url: jdbc:mysql://db:3306/bapsim_local?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: bapsim_user
    password: bapsim1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  
  h2:
    console:
      enabled: false

server:
  port: 8080

logging:
  level:
    com.bapsim: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Local development specific settings
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# SSAFY API 공통 설정
ssafy:
  api:
    baseUrl: https://finopenapi.ssafy.io/ssafy/api/v1/edu
    headers:
      institutionCode: "00100"
      fintechAppNo: "001"
      apiKey: "57daf5afceac4eb0a0ac387f5175c8fc"
      userKey: "3e349104-295e-4226-a87c-d8c1542e8110"
    endpoints:
      balanceInquiry: demandDeposit/inquireDemandDepositAccountBalance
      withdrawal: demandDeposit/updateDemandDepositAccountWithdrawal
      transactionHistory: demandDeposit/inquireTransactionHistoryList
    timeout:
      connect: 5000
      read: 10000
